from django.core.management.base import BaseCommand, CommandError
from .required import *

class Command(BaseCommand):
    def handle(self, *args, **options):
        for _ in range(1000):
            country = CountryFactory.create()
            country.save()
            region = RegionFactory.create()
            region.save()
            city = CityFactory.create()
            city.save()
            district = DistrictFactory.create()
            district.save()
            street = StreetFactory.create()
            street.save()
            maker = MakerFactory.create()
            maker.save()
            trade_name = TradeNameFactory.create()
            trade_name.save()
            category = CategoryFactory.create()
            category.save()
            measure = MeasureFactory.create()
            measure.save()
            packing = PackingFactory.create()
            packing.save()
            original = OriginalFactory.create()
            original.save()
            good = GoodFactory.create()
            good.save()
            department = DepartmentFactory.create()
            department.save()
            employee = EmployeeFactory.create()
            employee.save()
            currency = CurrencyFactory.create()
            currency.save()
            stock = StockFactory.create()
            stock.save()
            lot = LotFactory.create()
            lot.save()
            revaluation = RevaluationFactory.create()
            revaluation.save()
            agreement_status = AgreementStatusFactory.create()
            agreement_status.save()
            agreement = AgreementFactory.create()
            agreement.save()
